const BOARD_SIZE = 800;
const TILE_SIZE = BOARD_SIZE/10;
const OFFSET = (BOARD_SIZE - 7 * TILE_SIZE) / 2
const BOARD_SPEED = 10;
const FRAME_RATE = 25;
const ROTATE_SPEED = Math.PI/16;
module.exports = {TILE_SIZE, FRAME_RATE, BOARD_SIZE, OFFSET, BOARD_SPEED, ROTATE_SPEED};
